services:
  postgres:
    image: postgres:latest
    container_name: wisestyle-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wisestyle
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - wisestyle-network

  redis:
    image: redis:latest
    container_name: wisestyle-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - wisestyle-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: wisestyle-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - wisestyle-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: wisestyle-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - wisestyle-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: wisestyle-backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    networks:
      - wisestyle-network

volumes:
  postgres_data:
  redis_data:

networks:
  wisestyle-network:
    driver: bridge 