services:
  - type: web
    name: wisestyle-api
    env: docker
    rootDir: server
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: wisestyle-db
          property: connectionString
      - key: REDIS_URL
        value: "rediss://default:AYLWAAIjcDFmNTI2YmI4MTFiNWM0N2UyOTMwYjZjN2MyMDYyYjRjMHAxMA@suited-tahr-33494.upstash.io:6379"
      - key: JWT_SECRET
        value: "wisestyle-super-secret-jwt-key-2024"
      - key: JWT_EXPIRATION
        value: 24h
      - key: FRONTEND_URL
        value: https://wisestyle.vercel.app
      - key: NEXT_PUBLIC_SOCKET_URL
        value: https://wisestyle.vercel.app

databases:
  - name: wisestyle-db
    databaseName: wisestyle
    plan: free
