services:
  - type: web
    name: wisestyle-api
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: wisestyle-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: wisestyle-redis
          type: redis
          property: connectionString

  - type: redis
    name: wisestyle-redis
    ipAllowList: []
    plan: free

databases:
  - name: wisestyle-db
    databaseName: wisestyle
    plan: free
