services:
  - type: web
    name: wisestyle-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install --legacy-peer-deps && npm run build
    startCommand: cd server && npm run start:prod
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wisestyle-db
          property: connectionString
      - key: REDIS_URL
        value: "rediss://default:AYLWAAIjcDFmNTI2YmI4MTFiNWM0N2UyOTMwYjZjN2MyMDYyYjRjMHAxMA@suited-tahr-33494.upstash.io:6379"
      - key: JWT_SECRET
        value: "wisestyle-super-secret-jwt-key-2024"
      - key: PORT
        value: "3001"
      - key: NODE_ENV
        value: "production"
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: wisestyle-data
      mountPath: /data
      sizeGB: 1

databases:
  - name: wisestyle-db
    databaseName: wisestyle
    user: wisestyle
    plan: free
