services:
  - type: web
    name: wisestyle-api
    env: docker
    region: oregon
    plan: free
    buildCommand: |
      cd server
      docker build -t wisestyle-api .
    startCommand: docker run -p 3001:3001 wisestyle-api
    healthCheckPath: /health
    autoDeploy: true
    deployHook: ${DEPLOY_HOOK}
    numInstances: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wisestyle-db
          property: connectionString
      - key: REDIS_URL
        value: "rediss://default:AYLWAAIjcDFmNTI2YmI4MTFiNWM0N2UyOTMwYjZjN2MyMDYyYjRjMHAxMA@suited-tahr-33494.upstash.io:6379"
      - key: JWT_SECRET
        value: "wisestyle-super-secret-jwt-key-2024"
      - key: PORT
        value: "3001"
      - key: NODE_ENV
        value: "production"
    buildFilter:
      paths:
        - server/**
    routes:
      - type: rewrite
        source: /*
        destination: /server

databases:
  - name: wisestyle-db
    databaseName: wisestyle
    user: wisestyle
    plan: free
