[build]
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[service]
name = "wisestyle-api" 